apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sn7g4shoy-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sn7g4shoy-java-quarkus-gitops